name: npm-publish

on:
  pull_request:
    types:
      - closed
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    - run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
    # publish to NPM -> there is one caveat, continue reading for the fix
    - run: npm publish
      env:
        # Use a token to publish to NPM. See below for how to set it up
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
